### ISSUE TITLE
Add the menu search filter according to category and name

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#3]
Hi,
Have a look in this menu section. The client wants a feature to search for the menu. Add a filter to allow search by name. Add a filter according to snacks or breakfast and dinner.
1. Also make the New Entry and New Category button similar to that you added in the sidebar.( Similar to Front Access and Admin Access )
![image](https://user-images.githubusercontent.com/124490456/218261747-ca7d3e66-2a5d-4756-a93d-04753f37f821.png)

**Comment by indrajith76** [comment]
It's done
