### ISSUE TITLE
Redesign the book room feature so its responsive in both web and app
You have the freedom to place any field any where you like. 

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#38]
![Screenshot_2023-02-26-08-26-21-041_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389296-fb646ed1-bbd4-41c2-9e5a-a724920b59dd.jpg)

**Comment by indrajith76** [comment]
done
