### ISSUE TITLE
Client needs the feature to order food directly from phone so we need need to make order page responsive 


### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#39]
![Screenshot_2023-02-26-08-27-02-724_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389496-a13e443f-e528-4b9d-ba14-0480e7ce456c.jpg)

![Screenshot_2023-02-26-08-32-26-803_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389495-c1980383-bd86-4de8-bce0-f113fbd2a82b.jpg)

ReDesign how ever you wish but try to make it look good

**Comment by indrajith76** [comment]
done
