### ISSUE TITLE
Validate text input on the go

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#40]
Since we are already using daisy ui change all the text inputs and implement daisy ui text input
Client wants a different text inputs and buttons to make it look professional
Implement text input from daisy ui. We need to replace all text inputs and buttons with the ones on daisy ui.
When data is not entered make it form control without label. 
After some input make it green.
If data is of wrong type or field is empty make it red.
For eg: if field name is left empty make it red.
If in price or advance you type a letter instead of number make it red. And prevent form validation as well.
 Apply similar feature with all the screens i have attached 

![Screenshot_2023-02-26-08-37-16-236_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389746-5571aacc-c12f-4c7d-9b46-7b8a09f9b445.jpg)

![Screenshot_2023-02-26-08-27-02-724_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389892-534249e9-5ac3-4e9d-9383-01bda8402dd6.jpg)

![Screenshot_2023-02-26-08-32-26-803_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389894-21c3f81d-495c-4278-b110-da45e65758f3.jpg)

![Screenshot_2023-02-26-08-26-21-041_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389897-9f5aac3b-2b91-4648-9d08-91d8267f07dd.jpg)

![Screenshot_2023-02-26-08-47-16-248_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389918-6f180f64-9ac5-473b-9fc3-e7d55193a19d.jpg)

![Screenshot_2023-02-26-08-46-56-554_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389926-452e45d6-656d-4d0c-a0aa-e97b6365fb17.jpg)

![Screenshot_2023-02-26-08-47-07-375_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389927-cee24450-28ec-49a7-a983-726d8c5240d4.jpg)

![Screenshot_2023-02-26-08-47-02-432_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389925-ce97f27c-bc6b-4ace-b145-8ffdeb59463d.jpg)

![Screenshot_2023-02-26-08-47-58-863_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389972-c1979b6c-0191-4c84-9a94-26c3ef466a32.jpg)

![Screenshot_2023-02-26-08-48-51-416_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221389976-6f9107dc-a647-4565-b61f-eb937e9b8d31.jpg)

**Comment by indrajith76** [comment]
Done
