### ISSUE TITLE
Make the room and table cards responsive as well. Fit in two or three columns. 

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#41]
![Screenshot_2023-02-26-08-32-26-803_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390007-ffb7cbfd-a4a8-4f9e-b5da-ce898921349b.jpg)

![Screenshot_2023-02-26-08-26-34-252_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390009-b86a5680-ae96-4990-821a-a94b420a2022.jpg)

![Screenshot_2023-02-26-08-47-54-986_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390010-8294401c-639c-4150-ac5d-fc3635e827ae.jpg)

![Screenshot_2023-02-26-08-26-47-629_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390008-60be7c32-394e-4103-b3b2-37707168f1d7.jpg)

**Comment by indrajith76** [comment]
done
