### ISSUE TITLE
Make the navbar shown at all times in desktop view as well as mobile 

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#42]
![Screenshot_2023-02-26-08-52-33-222_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390091-ce4f700e-3338-46cc-a393-ffcfd85f3301.jpg)

**Comment by indrajith76** [comment]
What do you mean? I did not understand. Please describe
