### ISSUE TITLE
Migrate all the modals to daisy ui

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#43]
![Screenshot_2023-02-26-08-56-05-787_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390210-e743d277-cf97-41e8-b5cd-11951a159924.jpg)

![Screenshot_2023-02-26-08-56-49-294_com.android.chrome.jpg](https://user-images.githubusercontent.com/124490456/221390232-455371de-bc12-4a40-90c6-e7c6739ad4c7.jpg)

This includes all modals including add room, add order, book room, book order, etc. Kindly locate and feplace all modals to give a smooth animating effect

**Comment by indrajith76** [comment]
It's done. Some of modal is looks okay that's why I did not change those.
