### ISSUE TITLE
Make the DropDown button work in all of the following mentioned pages

### ISSUE THREAD

**Issue by ArkoSoftware** [ArkoSoftware/HotelYesSoftware#9]
Allow the feature to delete stock or menu.
Make the dropdown delete feature work in the following screens:
1. Stock Screen
2. Menu Screen
3. Vendor Screen
4. Asset Screen

![image](https://user-images.githubusercontent.com/124490456/218272052-67dce22f-fc42-4b66-a24e-91c2503d1786.png)

**Comment by indrajith76** [comment]
dropdown delete button is added
